### ISSUE TITLE
prop_weighted_cube supports Wake and Sleep as inputs

### ISSUE THREAD

**Issue by DrMeepster** [TeamSpen210/HammerAddons#81] opened 2020-05-01 21:57 UTC
`prop_weighted_cube` should have the `Wake` and `Sleep` inputs added to its FGD, as they do work on it.

**Comment by Luke18033** [comment] 2020-05-03 03:17
This would be somewhat related to #74 (inheriting stuff from prop_physics).

**Comment by TeamSpen210** [comment] 2020-05-03 10:48
It's a duplicate of that. It actually is a subclass, so it supports most of what that does.

**Closed by TeamSpen210** 2020-05-03 10:48 UTC
Labels: duplicate, enhancement
