### ISSUE TITLE
Any Game: Env_Dustpuff's icon is HUGE

### ISSUE THREAD

**Issue by lazyRares** [TeamSpen210/HammerAddons#118] opened 2021-03-23 00:20 UTC
![image](https://user-images.githubusercontent.com/33793448/112074172-1457b600-8b4c-11eb-8a0b-31b3e69cf8d5.png)
 the image is self explanatory

**Comment by Luke18033** [comment] 2021-03-23 00:22
It's a known issue, and isn't easily fixable. Hammer is hardcoded to use the `scale` keyvalue to resize an entity's sprite if it exists.

**Comment by Luke18033** [comment] 2021-03-23 00:22
Duplicate of #27.

**Comment by lazyRares** [comment] 2021-03-23 00:37
> Duplicate of #27.

Oh, well. why dont i just make a 64 x 64 version?

**Closed** 2021-03-23 02:29 UTC
